//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_LX_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorker()
        {
            this.tblWorker1 = new HashSet<tblWorker>();
        }
    
        public int WorkerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string JMBG { get; set; }
        public string PersonalIDNumber { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> GenderID { get; set; }
    
        public virtual tblGender tblGender { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblSector tblSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorker> tblWorker1 { get; set; }
        public virtual tblWorker tblWorker2 { get; set; }
    }
}
