//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_LX_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLocation
    {
        public int LocationID { get; set; }
        public string FullLocation { get; set; }
    }
}
