//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_LX_Milos_Peric
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkerDatabaseEntities : DbContext
    {
        public WorkerDatabaseEntities()
            : base("name=WorkerDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGender> tblGenders { get; set; }
        public virtual DbSet<tblLocation> tblLocations { get; set; }
        public virtual DbSet<tblSector> tblSectors { get; set; }
        public virtual DbSet<tblWorker> tblWorkers { get; set; }
        public virtual DbSet<vwLocation> vwLocations { get; set; }
        public virtual DbSet<vwManager> vwManagers { get; set; }
        public virtual DbSet<vwWorker> vwWorkers { get; set; }
    }
}
